openapi: 3.0.0
info:
  title: CoffeeShopOS API
  version: "1.0"
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: OK
